marketplace/apps/board/urls.py
from django.conf.urls import url

from marketplace.apps.board.views import (PostCreateView,
                                     PostDeleteView,
                                     PostDetailView,
                                     # PostListView,
                                     PostSearchView,
                                     PostUpdateView)


app_name = 'board'
urlpatterns = [
    url(r'^$', PostSearchView.as_view(), name='list'),
    url(r'^new/$', PostCreateView.as_view(), name='create'),
    url(r'^posts/$', PostSearchView.as_view(), name='list'),
    url(r'^posts/new/$', PostCreateView.as_view(), name='create'),
    url(r'^posts/(?P<slug>[-\w]+)/edit/$', PostUpdateView.as_view(), name='update'),
    url(r'^posts/(?P<slug>[-\w]+)/delete/$', PostDeleteView.as_view(), name='delete'),
    url(r'^posts/(?P<slug>[-\w]+)/$', PostDetailView.as_view(), name='detail'),
]

marketplace/apps/messaging/urls.py
from django.conf.urls import url

from marketplace.apps.messaging.views import (MessageCreateView,
                                        MessageDetailView,
                                        MessageListView,
                                        )


app_name = 'messaging'
urlpatterns = [
    url(r'^$', MessageListView.as_view(), name='inbox'),
    url(r'^new/(?P<slug>[-\w]+)', MessageCreateView.as_view(), name='new'),
    url(r'^(?P<slug>[-\w]+)/$', MessageDetailView.as_view(), name='detail'),
]

marketplace/apps/social/urls.py
from django.conf.urls import url

from marketplace.apps.social.views import (ReviewCreateView,
                                      ReviewDetailView,
                                      SocialProfileDetailView,
                                      SocialProfileSelfDetailView,
                                      # SocialProfileListView,
                                      SocialProfileUpdateView)


app_name = 'social'
urlpatterns = [
    # url(r'^$', SocialProfileListView.as_view(), name='list'),
    url(r'^profile/$', SocialProfileSelfDetailView.as_view(), name='detail'),
    url(r'^profile/(?P<slug>[-\w]+)/$', SocialProfileDetailView.as_view(), name='detail'),

    # Profile is updated in settings
    url(r'^settings/profile/$', SocialProfileUpdateView.as_view(), name='update'),

    # Review urls
    url(r'^reviews/new/(?P<slug>[-\w]+)/$', ReviewCreateView.as_view(), name='new_review'),
    url(r'^reviews/(?P<slug>[-\w]+)/$', ReviewDetailView.as_view(), name='review_detail'),
]

marketplace/urls.py
"""market URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Messaging app
    url(r'messaging/', include('marketplace.apps.messaging.urls')),

    # Remove logout confirmation
    # Note: Needs to be changed to redirect to ACCOUNT_LOGOUT_REDIRECT_URL
    # url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),

    # Social app
    url(r'^/', include('marketplace.apps.social.urls')),

    # Board app
    url(r'^/', include('marketplace.apps.board.urls')),

]

# URL for media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/templates/marketplace/base.html
{% load compress %}
{% load leaflet_tags %}
{% load staticfiles %}

<!doctype html>
<html lang="en">

<head>
  <title>  {{ cust.title }} &mdash; {% block title %}Title here{% endblock title %}</title>

  {% comment %} Meta tags {% endcomment %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Description goes here TODO">
  {% block meta %}{% endblock %}

  {% comment %}
    TODO: Favicons
  {% endcomment %}

  {% comment %} Customized Bootstrap build {% endcomment %}
  {% compress css %}
    <link rel="stylesheet" href="{% static 'scss/style.scss' %}" type="text/x-scss">
    {% leaflet_css plugins='forms' %}
  {% endcompress %}

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">

  {% comment %} Scripts {% endcomment %}
  <script src="../static/js/jquery-3.2.1.slim.min.js"></script>
  <script src="../static/js/popper.min.js"></script>
  <script src="../static/js/bootstrap.min.js"></script>
  {% leaflet_js plugins='forms' %}
  {% block extra_scripts %}{% endblock extra_scripts %}

  {% block extra_head %}{% endblock extra_head %}
</head>

<body>

{% comment %} Top navigation bar {% endcomment %}
<header class="navbar navbar-expand-sm navbar-dark bg-primary">
  <div class="container">
    <button class="navbar-toggler mr-2" type="button" data-toggle="collapse" data-target="#navItems">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a href="{% url 'board:list' %}" class="navbar-brand mr-auto">
        {% if c_logo %}
            <img src="{% static c_logo_path %}" height="30">
        {% else %}
            {{ c_title }}
        {% endif %}
    </a>
    <div class="collapse navbar-collapse flex-sm-row-reverse" id="navItems">
      <div class="navbar-nav">
        {# url_name is the named url e.g., 'social:update' #}
        {% with url_name=request.resolver_match.view_name %}
          {% if profile %}
            {% if profile.is_seller %}
              <a href="{% url 'board:create' %}" class="btn btn-outline-light mr-4"><i class="fa fa-plus mr-2" aria-hidden="true"></i>Create post</a>
            {% endif %}
            <div class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle active" role="button" data-toggle="dropdown">
                <i class="fa fa-user-circle mr-1" aria-hidden="true"></i>{{ profile }}
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                {% if profile.is_seller %}
                  <h5 class="dropdown-header">{{ profile }}</h5>
                  <a href="{% url 'social:detail' %}" class="dropdown-item">Your profile</a>
                  <div class="dropdown-divider"></div>
                {% endif %}
                <a href="{% url 'messaging:inbox' %}" class="dropdown-item">Messaging</a>
                <a href="{% url 'social:update' %}" class="dropdown-item">Settings</a>
                <a href="{% url 'account_logout' %}" class="dropdown-item">Sign out</a>
              </div>
            </div>
          {% else %}
            <a href="{% url 'account_login' %}" class="nav-item nav-link{% if url_name == 'account_login' %} active{% endif %}">Login</a>
            <a href="{% url 'account_signup' %}" class="nav-item nav-link{% if url_name == 'account_signup' %} active{% endif %}">Register</a>
          {% endif %}
        {% endwith %}
      </div>
    </div>
  </div>
</header>

{% comment %} Banner messages {% endcomment %}
{% for message in messages %}
  <div class="alert alert-{{ message.level_tag }} rounded-0 mb-0 alert-dismissible fade show" role="alert">
    <div class="container">
      <button type="button" class="close" data-dismiss="alert">
        <span>&times;</span>
      </button>
      {% if message.extra_tags %}
        {# extra_tags are used for an optional icon #}
        <i class="{{ message.extra_tags }} mr-1" aria-hidden="true"></i>
      {% endif %}
      <span>{{ message }}</span>
    </div>
  </div>
{% endfor %}

{% comment %} Page body {% endcomment %}
<div class="container mt-4" id="container">
  {% block content %}
  {% endblock content %}
</div>

{% comment %} Page footer {% endcomment %}
<footer class="navbar navbar-light bg-light mt-4">
  <div class="container">
    <span class="navbar-text">
      <small>Footer goes here</small>
    </span>
  </div>
</footer>

</body>

</html>