marketplace/apps/board/urls.py
from django.conf.urls import url

from marketplace.apps.board.views import (PostCreateView,
                                     PostDeleteView,
                                     PostDetailView,
                                     # PostListView,
                                     PostSearchView,
                                     PostUpdateView)


app_name = 'board'
urlpatterns = [
    url(r'^$', PostSearchView.as_view(), name='list'),
    url(r'^new/$', PostCreateView.as_view(), name='create'),
    url(r'^posts/$', PostSearchView.as_view(), name='list'),
    url(r'^posts/new/$', PostCreateView.as_view(), name='create'),
    url(r'^posts/(?P<slug>[-\w]+)/edit/$', PostUpdateView.as_view(), name='update'),
    url(r'^posts/(?P<slug>[-\w]+)/delete/$', PostDeleteView.as_view(), name='delete'),
    url(r'^posts/(?P<slug>[-\w]+)/$', PostDetailView.as_view(), name='detail'),
]

marketplace/apps/messaging/urls.py
from django.conf.urls import url

from marketplace.apps.messaging.views import (MessageCreateView,
                                        MessageDetailView,
                                        MessageListView,
                                        )


app_name = 'messaging'
urlpatterns = [
    url(r'^$', MessageListView.as_view(), name='inbox'),
    url(r'^new/(?P<slug>[-\w]+)', MessageCreateView.as_view(), name='new'),
    url(r'^(?P<slug>[-\w]+)/$', MessageDetailView.as_view(), name='detail'),
]

marketplace/apps/social/urls.py
from django.conf.urls import url

from marketplace.apps.social.views import (ReviewCreateView,
                                      ReviewDetailView,
                                      SocialProfileDetailView,
                                      SocialProfileSelfDetailView,
                                      # SocialProfileListView,
                                      SocialProfileUpdateView)


app_name = 'social'
urlpatterns = [
    # url(r'^$', SocialProfileListView.as_view(), name='list'),
    url(r'^profile/$', SocialProfileSelfDetailView.as_view(), name='detail'),
    url(r'^profile/(?P<slug>[-\w]+)/$', SocialProfileDetailView.as_view(), name='detail'),

    # Profile is updated in settings
    url(r'^settings/profile/$', SocialProfileUpdateView.as_view(), name='update'),

    # Review urls
    url(r'^reviews/new/(?P<slug>[-\w]+)/$', ReviewCreateView.as_view(), name='new_review'),
    url(r'^reviews/(?P<slug>[-\w]+)/$', ReviewDetailView.as_view(), name='review_detail'),
]

marketplace/urls.py
"""market URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Messaging app
    url(r'messaging/', include('marketplace.apps.messaging.urls')),

    # Remove logout confirmation
    # Note: Needs to be changed to redirect to ACCOUNT_LOGOUT_REDIRECT_URL
    # url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),

    # Social app
    url(r'^/', include('marketplace.apps.social.urls')),

    # Board app
    url(r'^/', include('marketplace.apps.board.urls')),

]

# URL for media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/apps/social/models.py
from django.db import models
from django_extensions.db.models import (ActivatorModel,
                                         TimeStampedModel)
from django.urls import reverse

from djgeojson.fields import PointField

from marketplace.apps.core.models import (RandomSlugModel,
                                     UserProfile)


# Model for user-to-user reviews.
class Review(RandomSlugModel, TimeStampedModel):
    reviewer = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='reviewer')
    reviewee = models.ForeignKey(UserProfile, default=1, on_delete=models.CASCADE, related_name='reviewee')
    title = models.CharField(max_length=128)
    SCORE_CHOICES = [
                    (1, '1'),
                    (2, '2'),
                    (3, '3'),
                    (4, '4'),
                    (5, '5'),
        ]
    score = models.IntegerField(choices=SCORE_CHOICES, default=4)
    body = models.TextField(max_length=5000)
    def get_absolute_url(self):
        return reverse('messaging:review_deteail', kwargs={'slug': self.slug})


# The SocialProfile is a model used by Sellers through which they detail themselves
# and/or provide additional information on their services.
class SocialProfile(RandomSlugModel):
    owner = models.OneToOneField(UserProfile, on_delete=models.CASCADE, related_name='social')

    avatar = models.ImageField(null=True, blank=True)
    tagline = models.CharField(max_length=150, blank=True)
    bio = models.TextField(max_length=2000, blank=True)

    # Location to be changed here, same as in posts.
    location = PointField()

    def get_absolute_url(self):
        return reverse('social:detail', kwargs={'slug': self.slug})

marketplace/apps/social/forms.py
from django import forms

from crispy_forms import (bootstrap,
                          layout)
from crispy_forms.helper import FormHelper
from leaflet.forms.widgets import LeafletWidget

from marketplace.apps.core.models import UserProfile
from marketplace.apps.social.models import (Review,
                                       SocialProfile)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['reviewee', 'score', 'title', 'body']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = layout.Layout(
            layout.Fieldset(
                '',
                layout.Field('reviewee', readonly=True),
                'score',
                'title',
                'body',
            ),
            bootstrap.FormActions(
                layout.Submit('submit', 'Post Review', css_class='btn btn-success'),
            )
        )
        self.helper.form_tag = False


class SocialProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = SocialProfile
        fields = ['avatar', 'tagline', 'bio', 'location']
        widgets = {'location': LeafletWidget()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.layout = layout.Layout(
            layout.Fieldset(
                '',
                'avatar',
                'tagline',
                'bio',
                'location'
            ),
            bootstrap.FormActions(
                layout.Submit('submit', 'Update profile', css_class='btn btn-success'),
            )
        )


class UserProfileForm(forms.Form):
    # This form is used in registration to automatically create both UserProfile and SocialProfile objects
    # Note that this is NOT the form actually seen by the user

    def signup(self, request, user):
        # Automatically create user profile for every user
        profile = UserProfile.objects.create(user=user, type=self.cleaned_data['type'], name=self.cleaned_data['name'])

        # Create an empty SocialProfile if the user is a seller
        if profile.is_seller:
            SocialProfile.objects.create(owner=profile)

marketplace/apps/social/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import (DetailView,
                                  FormView,
                                  ListView,
                                  RedirectView,
                                  UpdateView)
from extra_views import (CreateWithInlinesView)
from marketplace.apps.board.models import Post
from marketplace.apps.core.mixins import (CreateWithOwnerMixin,
                                     CreateWithReviewerMixin,
                                     CreateWithSenderMixin,
                                     OwnerRequiredMixin,
                                     SellerRequiredMixin)
from marketplace.apps.core.models import UserProfile
from marketplace.apps.social.forms import (ReviewForm,
                                      SocialProfileUpdateForm,)
from marketplace.apps.social.models import (Review,
                                       SocialProfile,)


# Create a new Review
class ReviewCreateView(CreateWithReviewerMixin, CreateWithInlinesView):
    model = Review
    form_class = ReviewForm
    template_name = 'social/review_form.html'

    def get_form(self, form_class):
        form = super().get_form(ReviewForm)
        reviewee = UserProfile.objects.filter(slug=self.kwargs['slug'])
        if len(reviewee) > 0:
            form.fields['reviewee'].queryset = reviewee
        else:
            raise Http404("Invalid Reviewee attempted.")
        return form

    def get_success_url(self):
        messages.success(self.request, 'Review posted!', extra_tags='fa fa-check')
        return reverse('board:list')

#TODO: ReviewUpdateView

# View a single review. Currently, this isn't part of the site, but may be used later
# if, for example, review subjects can respond to a review.
class ReviewDetailView(DetailView):
    model = Review
    template_name = 'social/review_detail.html'

# Viewing a seller's own profile
class SocialProfileSelfDetailView(SellerRequiredMixin, DetailView):
    model = SocialProfile
    context_object_name = 'social_profile'
    template_name = 'social/profile_detail.html'

    def get_object(self, *args, **kwargs):
        return SocialProfile.objects.get(owner=self.request.profile)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts_list'] = Post.objects.filter(owner=self.request.profile).order_by("-modified")
        context['reviews_list'] = Review.objects.filter(reviewee=self.request.profile).order_by("-modified")
        if len(context['reviews_list']) > 0:
            average = context['reviews_list'].aggregate(Avg('score'))['score__avg']
        else:
            average = 0
        average_str = []
        val = 0.00
        ''' Django HTML has a hard time looping through numerical values, so to display the score
        we convert it to a string, (5 stars is 'fffff', 0 is 'eeeee') and then iterate through the
        string to display stars on a seller's page. Hacky to be sure, but I wasn't able to find a
        more elegant alternative'''
        while val < 5:
            if val + 1 <= average:
                average_str.append('f')
            elif val + 0.5 <= average:
                average_str.append('h')
            else:
                average_str.append('e')
            val += 1
        context['average_str'] = average_str
        context['average'] = average
        return context

# Same as the above, but for viewing another seller.
class SocialProfileDetailView(DetailView):
    model = SocialProfile
    context_object_name = 'social_profile'
    template_name = 'social/profile_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = SocialProfile.objects.get(slug=self.kwargs['slug']).owner
        context['posts_list'] = Post.objects.filter(owner=user).order_by("-modified")
        context['reviews_list'] = Review.objects.filter(reviewee=user).order_by("-modified")
        if len(context['reviews_list']) > 0:
            average = context['reviews_list'].aggregate(Avg('score'))['score__avg']
        else:
            average = 0
        average_str = []
        val = 0.00
        while val < 5:
            if val + 1 <= average:
                average_str.append('f')
            elif val + 0.5 <= average:
                average_str.append('h')
            else:
                average_str.append('e')
            val += 1
        context['average_str'] = average_str
        context['average'] = average
        return context

# Update a profile.
class SocialProfileUpdateView(SellerRequiredMixin, OwnerRequiredMixin, UpdateView):
    model = SocialProfile
    form_class = SocialProfileUpdateForm
    template_name = 'social/profile_update_form.html'

    def get_object(self, *args, **kwargs):
        return SocialProfile.objects.get(owner=self.request.profile)

    def get_success_url(self):
        messages.success(self.request, 'Seller profile updated!', extra_tags='fa fa-check')
        return reverse('social:update')

marketplace/templates/marketplace/social/browse.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}All Sellers{% endblock title %}

{% block content %}
  <div class="row mb-4">
    <div class="col-12">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." aria-label="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-secondary" type="button">Go!</button>
        </span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      {% if object_list %}
        <div class="card-columns">
          {% for user_profile in object_list %}
            <div class="card">
              <img class="card-img-top" src="{% static 'img/placeholder.svg' %}">
              <div class="card-body">
                <h5 class="card-title mb-1"><a href="{% url 'board:detail' slug=user_profile.slug %}">{{ user_profile.name|truncatechars:60 }}</a></h5>
                <h6 class="text-muted mb-3"><small>by <a href="#" class="text-muted">{{ user_profile.location }}</a></small></h6>
                <h5 class="">${{ user_profile.bio|truncatechars:100}}</h5>
              </div>
            </div>
          {% endfor %}
        </div>
      {% else %}
        <h2 class="text-muted text-center my-5">
          No user profiles here! :(
        </h2>
      {% endif %}
    </div>
  </div>

  {% comment %} Pagination navigation {% endcomment %}
  {% if is_paginated %}
    <div class="row">
      <div class="col-12">
        <nav>
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">Previous</span>
              </li>
            {% endif %}

            {% for i in paginator.page_range %}
              {% if  i == page_obj.number %}
                <li class="page-item active">
                  <span class="page-link">{{ i }}</span>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
              {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">Next</span>
              </li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>
  {% endif %}
{% endblock content %}

marketplace/templates/marketplace/social/profile_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{{ social_profile.owner }}{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-12 col-sm-3 mb-4">
      <img class="rounded w-100" src="{% static 'img/placeholder.svg' %}">
    </div>
    <div class="col-12 col-sm-9 mb-4">
      <h2>{{ social_profile.owner }}</h2>
      {% if social_profile.tagline %}
        <p><em>{{ social_profile.tagline }}</em></p>
      {% endif %}
      <p class="text-muted">
        <i class="fa fa-map-marker mr-2" aria-hidden="true"></i>Location&emsp;|&emsp;Other information
        <br>
        <span class="text-warning">
            <a href="{% url 'social:new_review' slug=object.owner.slug%}">
            {% for c in average_str %}
                {% if c == 'f' %}
                  <i class="fa fa-star" aria-hidden="true"></i>
                {% elif c == 'h' %}
                  <i class="fa fa-star-half-o" aria-hidden="true"></i>
                {% else %}
                  <i class="fa fa-star-o" aria-hidden="true"></i>
                {% endif %}
            {% endfor %}
            </a>
        </span>
        <span class="ml-1">
            {% if average > 0 %}
                {{ average }} Avg.</span>
            {% else %}
                No reviews.
            {% endif %}
          <br>
          {% if profile %}
              {% if profile != object.owner %}
                  <a href="{% url 'messaging:new' slug=object.owner.slug%}">Message me!</a>
                  <br>
                  <a href="{% url 'social:new_review' slug=object.owner.slug%}">Write a review!</a>
              {% endif %}
        {% endif %}
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <ul class="nav nav-tabs mb-4" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#sellerPosts" role="tab">Posts ({{ posts_list|length }})</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#sellerReviews" role="tab">Reviews</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#sellerAbout" role="tab">About</a>
        </li>
      </ul>
      <div class="tab-content" id="sellerTabs">
        <div class="tab-pane fade show active" id="sellerPosts" role="tabpanel">
          {% if posts_list %}
            {% include 'board/posts_widget.html' with posts_list=posts_list %}
          {% else %}
            <h2 class="text-muted text-center my-5">
              No posts yet!
            </h2>
          {% endif %}
        </div>
        <div class="tab-pane fade" id="sellerReviews" role="tabpanel">
          {% include 'social/review_list_widget.html' with review_list=review_list %}
        </div>
        <div class="tab-pane fade" id="sellerAbout" role="tabpanel">
          {% if social_profile.bio %}
            {{ social_profile.bio }}
          {% else %}
            <em>This seller likes to keep an air of mystery about them...</em>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-12">
    </div>
  </div>
{% endblock content %}

marketplace/templates/marketplace/social/profile_update_form.html
{% extends 'settings/settings_base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}Seller Profile{% endblock title %}

{% block page_title %}Seller Profile{% endblock page_title %}

{% block page_content %}
  <p class="lead"> Add information to help sellers learn about you. </p>
  {% crispy form %}
{% endblock page_content %}

marketplace/templates/marketplace/social/review_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load staticfiles %}

{% block title %}Review Detail{% endblock title %}

{% block content %}

{% endblock content %}

marketplace/templates/marketplace/social/review_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}Post Review{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <h3>Post Review!</h3>
      <form method="post">
        {% crispy form %}
      </form>
    </div>
  </div>
{% endblock content %}

marketplace/templates/marketplace/social/review_list_widget.html
{% if reviews_list %}
    <div class="card-deck">
      {% for review in reviews_list %}
        <div class="card w3-hover-shadow" style="min-width: 50%; margin:10px; float:none;">
          <div class="card-body">
            <h5 class="card-title">{{ review.title }}</h5>
              <span class="text-warning">
                  <!- numeric loops are a huge pain in django, please forgive this weak solution>
                  {% if review.score == 5 %}
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                  {% elif review.score == 4%}
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                {% elif review.score == 3%}
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                {% elif review.score == 2%}
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                {% elif review.score == 1%}
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                  {% endif %}
                </span>
            <h6 class="text-muted mb-3"><small>by <a class="text-muted">{{ review.reviewer.name }}</a></small></h6>
            <p class="">{{ review.body|truncatechars:300 }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
{% else %}
    <h2 class="text-muted text-center my-5">
            No Reviews
    </h2>
{% endif %}