marketplace/apps/social/urls.py
from django.conf.urls import url

from marketplace.apps.social.views import (ReviewCreateView,
                                      ReviewDetailView,
                                      SocialProfileDetailView,
                                      SocialProfileSelfDetailView,
                                      # SocialProfileListView,
                                      SocialProfileUpdateView)


app_name = 'social'
urlpatterns = [
    # url(r'^$', SocialProfileListView.as_view(), name='list'),
    url(r'^profile/$', SocialProfileSelfDetailView.as_view(), name='detail'),
    url(r'^profile/(?P<slug>[-\w]+)/$', SocialProfileDetailView.as_view(), name='detail'),

    # Profile is updated in settings
    url(r'^settings/profile/$', SocialProfileUpdateView.as_view(), name='update'),

    # Review urls
    url(r'^reviews/new/(?P<slug>[-\w]+)/$', ReviewCreateView.as_view(), name='new_review'),
    url(r'^reviews/(?P<slug>[-\w]+)/$', ReviewDetailView.as_view(), name='review_detail'),
]

marketplace/urls.py
"""market URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Messaging app
    url(r'messaging/', include('marketplace.apps.messaging.urls')),

    # Remove logout confirmation
    # Note: Needs to be changed to redirect to ACCOUNT_LOGOUT_REDIRECT_URL
    # url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),

    # Social app
    url(r'^/', include('marketplace.apps.social.urls')),

    # Board app
    url(r'^/', include('marketplace.apps.board.urls')),

]

# URL for media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/templates/marketplace/settings/settings_base.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Settings{% endblock title %}

{% block content %}
  {% comment %}Side bar containing all settings{% endcomment %}
  <div class="row">
    <div class="col-12 col-sm-3">
      <div class="card mb-3">
        <div class="card-header">Seller Settings</div>
        <div class="list-group list-group-flush">
          {% with url_name=request.resolver_match.view_name %}
            <a href="{% url 'social:update' %}" class="list-group-item list-group-item-action{% if url_name == 'social:update' %} active{% endif %}">Profile</a>
          {% endwith %}
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-header">Account Settings</div>
        <div class="list-group list-group-flush">
          {% with url_name=request.resolver_match.view_name %}
            <a href="{% url 'account_email' %}" class="list-group-item list-group-item-action{% if url_name == '' %} active{% endif %}">Emails</a>
            <a href="{% url 'account_change_password' %}" class="list-group-item list-group-item-action{% if url_name == '' %} active{% endif %}">Password</a>
          {% endwith %}
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-9">
      <h3>{% block page_title %}{% endblock page_title %}</h3>
      <hr>
      {% block page_content %}
      {% endblock page_content %}
    </div>
  </div>
{% endblock content %}