marketplace/apps/board/urls.py
from django.conf.urls import url

from marketplace.apps.board.views import (PostCreateView,
                                     PostDeleteView,
                                     PostDetailView,
                                     # PostListView,
                                     PostSearchView,
                                     PostUpdateView)


app_name = 'board'
urlpatterns = [
    url(r'^$', PostSearchView.as_view(), name='list'),
    url(r'^new/$', PostCreateView.as_view(), name='create'),
    url(r'^posts/$', PostSearchView.as_view(), name='list'),
    url(r'^posts/new/$', PostCreateView.as_view(), name='create'),
    url(r'^posts/(?P<slug>[-\w]+)/edit/$', PostUpdateView.as_view(), name='update'),
    url(r'^posts/(?P<slug>[-\w]+)/delete/$', PostDeleteView.as_view(), name='delete'),
    url(r'^posts/(?P<slug>[-\w]+)/$', PostDetailView.as_view(), name='detail'),
]

marketplace/apps/messaging/urls.py
from django.conf.urls import url

from marketplace.apps.messaging.views import (MessageCreateView,
                                        MessageDetailView,
                                        MessageListView,
                                        )


app_name = 'messaging'
urlpatterns = [
    url(r'^$', MessageListView.as_view(), name='inbox'),
    url(r'^new/(?P<slug>[-\w]+)', MessageCreateView.as_view(), name='new'),
    url(r'^(?P<slug>[-\w]+)/$', MessageDetailView.as_view(), name='detail'),
]

marketplace/apps/social/urls.py
from django.conf.urls import url

from marketplace.apps.social.views import (ReviewCreateView,
                                      ReviewDetailView,
                                      SocialProfileDetailView,
                                      SocialProfileSelfDetailView,
                                      # SocialProfileListView,
                                      SocialProfileUpdateView)


app_name = 'social'
urlpatterns = [
    # url(r'^$', SocialProfileListView.as_view(), name='list'),
    url(r'^profile/$', SocialProfileSelfDetailView.as_view(), name='detail'),
    url(r'^profile/(?P<slug>[-\w]+)/$', SocialProfileDetailView.as_view(), name='detail'),

    # Profile is updated in settings
    url(r'^settings/profile/$', SocialProfileUpdateView.as_view(), name='update'),

    # Review urls
    url(r'^reviews/new/(?P<slug>[-\w]+)/$', ReviewCreateView.as_view(), name='new_review'),
    url(r'^reviews/(?P<slug>[-\w]+)/$', ReviewDetailView.as_view(), name='review_detail'),
]

marketplace/urls.py
"""market URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Messaging app
    url(r'messaging/', include('marketplace.apps.messaging.urls')),

    # Remove logout confirmation
    # Note: Needs to be changed to redirect to ACCOUNT_LOGOUT_REDIRECT_URL
    # url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),

    # Social app
    url(r'^/', include('marketplace.apps.social.urls')),

    # Board app
    url(r'^/', include('marketplace.apps.board.urls')),

]

# URL for media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/apps/board/models.py
from django.db import models
from django.db.models import Q
from django.urls import reverse

from django_extensions.db.models import (ActivatorModel,
                                         TimeStampedModel)
from djgeojson.fields import PointField
from tagulous.models import TagField

from marketplace.apps.core.models import (RandomSlugModel,
                                     UserProfile)


class PostManager(models.Manager):
    def search(self, **kwargs):
        qs = super().get_queryset()

        # TODO:
        # Split query into words, case insensitive search each field:
        # owner name, title, body, tags, location

        if 'query' in kwargs:
            query = kwargs['query']
            qs = qs.filter(Q(title__icontains=query) | Q(body__icontains=query))

        if 'tags' in kwargs:
            tags = kwargs['tags']
            # Filter to posts with tags in the provided set
            qs = qs.filter(tags__name__in=tags)

        return qs


# Posts submitted by users on the site.
class Post(RandomSlugModel, TimeStampedModel):
    UNIT_CHOICES = (
        ('pound', 'POUND'),
        ('gallon', 'GALLON'),
        ('each', 'EACH'),
    )

    # todo: custom queryset to get active posts
    objects = PostManager()

    owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    # todo: Remove activatormodel?

    title = models.CharField(max_length=300)
    body = models.TextField(max_length=5000)

    # TODO: Use autocomplete_initial=True and specify preset tags?
    tags = TagField(max_count=10, force_lowercase=True, space_delimiter=False, blank=True)

    price = models.DecimalField(max_digits=7, decimal_places=2)
    unit = models.CharField(max_length=80, choices=UNIT_CHOICES, default='each')

    # location = models.CharField(max_length=5)
    location = PointField()

    def get_absolute_url(self):
        return reverse('board:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title + " - $" + str(self.price)


class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(blank=True)

marketplace/apps/board/forms.py
from django import forms

from crispy_forms import (bootstrap,
                          layout)
from crispy_forms.helper import FormHelper

from leaflet.forms.widgets import LeafletWidget

from marketplace.apps.board.models import Post

# Form to handle the niput of images.
class ImageHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.layout = Layout(
        #     'image'
        # )
        # TODO: Template for image view
        self.template = 'bootstrap/table_inline_formset.html'
        self.form_tag = False
        self.disable_csrf = True

# Post Input
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'tags', 'price', 'unit', 'location']
        widgets = {'location': LeafletWidget()}

    # Appearance of the Form
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.layout = layout.Layout(
            layout.Fieldset(
                '',
                layout.Field('title', placeholder='A snappy title'),
                'body',
                'tags',
                bootstrap.PrependedAppendedText('price', '$', 'USD'),
                'unit',
                'location'
            ),
            bootstrap.FormActions(
                layout.Submit('submit', 'Create post', css_class='btn btn-success'),
            )
        )
        self.helper.form_tag = False


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'tags', 'price', 'unit', 'location']
        widgets = {'location': LeafletWidget()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # TODO: Don't repeat from the PostForm
        self.helper = FormHelper(self)
        self.helper.layout = layout.Layout(
            layout.Fieldset(
                '',
                layout.Field('title', placeholder='A snappy title'),
                'body',
                'tags',
                bootstrap.PrependedText('price', '$'),
                'unit',
                'location'
            ),
            bootstrap.FormActions(
                layout.Submit('submit', 'Update post', css_class='btn btn-success'),
                layout.HTML('<a class="btn btn-outline-secondary" href="{% url "board:detail" slug=object.slug %}">Cancel</a>'),
            )
        )
        self.helper.form_tag = False

marketplace/apps/board/views.py
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q
from django.views.generic import (DeleteView,
                                  DetailView,
                                  ListView,
                                  TemplateView)

from extra_views import (CreateWithInlinesView,
                         InlineFormSet,
                         UpdateWithInlinesView)
from functools import reduce
from itertools import chain
from operator import and_, or_
from marketplace.apps.board.forms import (ImageHelper,
                                     PostForm,
                                     PostUpdateForm)
from marketplace.apps.board.models import (Post,
                                      PostImage)
from marketplace.apps.core.mixins import (CreateWithOwnerMixin,
                                     OwnerRequiredMixin,
                                     SellerRequiredMixin)


class ImagesInline(InlineFormSet):
    model = PostImage
    fields = ['image']
    extra = 5
    max_num = 5
    # can_delete = False


class PostCreateView(CreateWithOwnerMixin, SellerRequiredMixin, CreateWithInlinesView):
    model = Post
    inlines = [ImagesInline]
    form_class = PostForm
    template_name = 'board/post_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['image_helper'] = ImageHelper()
        return context

    def get_success_url(self):
        messages.success(self.request, 'Post created!', extra_tags='fa fa-check')
        return self.object.get_absolute_url()


class PostDeleteView(OwnerRequiredMixin, DeleteView):
    model = Post
    # TODO: Can this use a form?
    template_name = 'board/post_confirm_delete.html'

    def get_success_url(self):
        messages.success(self.request, 'Post deleted!', extra_tags='fa fa-check')
        return reverse('board:list')


class PostDetailView(DetailView):
    model = Post
    template_name = 'board/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get most similar posts by tags
        # TODO: Also weight by distance
        # TODO: Search for posts with query based on this one
        context['similar_posts'] = self.model.objects.search(tags=self.object.tags.get_tag_list()).exclude(id=self.object.id)[:4]
        return context

# View for displaying searches
class PostSearchView(ListView):
    model = Post
    template_name = 'board/post_list.html'
    # No pagination for now, breaks searches
    # paginate_by = 8

    # Get the more specific results
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q', '')
        if query != '':
            sort_rule = self.request.GET.get('sort')
            sort_type = 'modified'
            if sort_rule:
                if sort_rule == 'date-newest':
                    sort_type = ('modified')
                elif sort_rule == 'date-oldest':
                    sort_type = ('-modified')
                elif sort_rule == 'price-lowest':
                    sort_type = ('price')
                elif sort_rule == 'price-highest':
                    sort_type = ('-price')
            search_terms = query.split()
            list = self.model.objects.filter(reduce(or_, [Q(title__icontains=term) | Q(tags__name=term) \
                                                         for term in search_terms])).order_by(sort_type, 'title')
            # If we were using postgres, this could be done by adding distinct to the end of the preceeding line.
            # In the meantime, here's a slightly longer solution.
            seen = []
            seen_add = seen.append
            list = [obj for obj in list if not (obj in seen or seen_add(obj))]
            context['post_list'] = list
        else:
            context['post_list'] = []
        return context

    # Get the more general results.
    def get_queryset(self):
        # TODO: Pre-process search query for better usability

        query = self.request.GET.get('q', '')

        # Sort by specified rule, then title
        sort_rule = self.request.GET.get('sort')
        sort_type = 'modified'
        if sort_rule:
            if sort_rule == 'date-newest':
                sort_type = ('modified')
            elif sort_rule == 'date-oldest':
                sort_type = ('-modified')
            elif sort_rule == 'price-lowest':
                sort_type = ('price')
            elif sort_rule == 'price-highest':
                sort_type = ('-price')

        if query != '':
            search_terms = query.split()
            qs = self.model.objects.order_by(sort_type, 'title')
            for term in search_terms:
                qs = qs.filter(Q(title__icontains=term) | Q(tags__name__icontains=term))
            # If we were using postgres, this could be done by adding distinct to the end of the preceeding line.
            # In the meantime, here's a slightly longer solution.
            seen = []
            seen_add = seen.append
            qs = [obj for obj in qs if not (obj in seen or seen_add(obj))]
        else:
            qs = self.model.objects.order_by(sort_type, 'title')
        return qs


class PostUpdateView(OwnerRequiredMixin, UpdateWithInlinesView):
    model = Post
    inlines = [ImagesInline]
    form_class = PostUpdateForm
    template_name = 'board/post_update_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['image_helper'] = ImageHelper()
        return context

    def get_success_url(self):
        messages.success(self.request, 'Post updated!', extra_tags='fa fa-check')
        return self.object.get_absolute_url()

marketplace/templates/marketplace/board/post_card_widget.html
{% load staticfiles %}
{% load humanize %}

<div class="card mb-4">
  {% if post.images.all %}
    <img class="card-img-top" src="{{ post.images.first.image.url }}">
  {% else %}
    <img class="card-img-top" src="{% static 'img/placeholder.svg' %}">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title mb-1"><a href="{% url 'board:detail' slug=post.slug %}">{{ post.title|truncatechars:60 }}</a></h5>
    <h6 class="text-muted mb-3"><small>by <a href="{% url 'social:detail' slug=post.owner.social.slug %}" class="text-muted">{{ post.owner }}</a></small></h6>
    <h5 class="">${{ post.price|intcomma }} /{{ post.unit }}</h5>
  </div>
</div>

marketplace/templates/marketplace/board/post_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}Delete Post{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <h3>Do you really want to delete this post?</h3>
      {{ form }}
      <form role="form" action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-danger">Delete post</button>
        <a class="btn btn-outline-secondary" href="{% url 'board:detail' slug=object.slug %}">Cancel</a>
      </form>
    </div>
  </div>
{% endblock content %}

marketplace/templates/marketplace/board/post_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load staticfiles %}

{% block title %}Detail{% endblock title %}

{% block content %}
  {% comment %}
  TODO: Poster profile snippet
  <div class="row">
    <div class="col-12 d-flex">
      <img class="rounded h-100 mr-4" src="{% static 'img/placeholder.svg' %}">
      <h4>{{ object.owner }}</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <hr>
    </div>
  </div>
  {% endcomment %}
  {% if profile == post.owner %}
    <div class="row mb-3">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Last modified {{ post.modified|naturaltime }}.</h5>
            <p class="card-text text-muted"></p>
            <a class="card-link" href="{% url 'board:update' slug=post.slug %}" role="button">Edit Post</a>
            <a class="card-link text-danger" href="{% url 'board:delete' slug=post.slug %}" role="button">Delete Post</a>
          </div>
        </div>
      </div>
    </div>
  {% endif %}

  <div class="row">
    <div class="col-12 col-sm-7">
      <div id="imageCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          {% for image in post.images.all %}
            <li data-target="#imageCarousel" data-slide-to="{{ forloop.counter0 }}"{% if forloop.first %} class="active"{% endif %}></li>
          {% endfor %}
        </ol>
        <div class="carousel-inner rounded">
          {% for image in object.images.all %}
            <div class="carousel-item{% if forloop.first %} active{% endif %}">
              <img class="d-block w-100" src="{{ image.image.url }}" alt="First slide">
            </div>
          {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#imageCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#imageCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <div class="col-12 col-sm-5">
      <h2>{{ object.title}}</h2>
      <h4 class="mt-3"><span class="font-weight-bold">${{ post.price }}</span> <small>/{{ object.unit }}</small></h4>
        <p class="text-muted">by <a href="{% url 'social:detail' slug=post.owner.social.slug %}">{{ post.owner }}</a></p>
      <a class="btn btn-primary btn-block mt-5" href="{% url 'messaging:new' slug=post.owner.slug %}" role="button">Message Seller</a>
      <hr>
      <h5>Description</h5>
      <p class="text-muted">{{ post.body }}</p>
    </div>
  </div>

  {% if post.tags.all %}
  <div class="row mt-3">
    <div class="col-12">
      <hr>
      <h5>Tags</h5>
      {# TODO: Make tags clickable, bring to post list filtered by this tag #}
      <h3>
      {% for tag in post.tags.all %}
          <a href="#" class="badge badge-pill badge-primary">{{ tag.name }}</a>
      {% endfor %}
      </h3>
    </div>
  </div>
  {% endif %}

  {% if similar_posts %}
  <div class="row mt-3">
    <div class="col-12">
      <hr>
      <h5>Similar Posts</h5>
      <div class="card-deck">
        {% for p in similar_posts %}
          {% include 'board/post_card_widget.html' with post=p %}
        {% endfor %}
      </div>
    </div>
  </div>
  {% endif %}
{% endblock content %}

marketplace/templates/marketplace/board/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}Create Post{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <h3>Create Post</h3>
      <form method="post" enctype="multipart/form-data">
        {% for image in inlines %}
          {% crispy image image_helper %}
        {% endfor %}
        {% crispy form %}
      </form>
    </div>
  </div>
{% endblock content %}

marketplace/templates/marketplace/board/post_list.html
{% extends 'base.html' %}
{% load geojson_tags %}
{% load leaflet_tags %}
{% load staticfiles %}

{% block title %}All Listings{% endblock title %}

{% block content %}
  <div class="row mb-4">
    <div class="col-12">
      <script type="text/javascript">
        var collection = {{ object_list|geojsonfeature:':location'|safe }};
        function map_init(map, options) {
            L.geoJson(collection).addTo(map);
        }
      </script>
      {% leaflet_map "main" callback="window.map_init" %}
    </div>
  </div>
  <div class="row mb-4">
    <div class="col-12">
      <form class="input-group" action="{% url 'board:list' %}" method="get" accept-charset="utf-8">
        <input class="form-control" name="q" type="text" placeholder="Search for...">
        <select class="col-xs" name="sort" type="text">
          <option value = "date-newest" disabled selected hidden>Sort by...</option>
          <option value="date-newest">Date (newest first)</option>
          <option value="date-oldest">Date (oldest first)</option>
          <option value="price-lowest">Price (lowest first)</option>
          <option value="price-highest">Price (highest first)</option>
        </select>
        <span class="input-group-btn">
          <button class="btn btn-secondary" type="submit">
            <i class="fa fa-search" aria-hidden="true"></i>
          </button>
        </span>
      </form>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      {% if object_list %}
        {% include 'board/posts_widget.html' with posts_list=object_list %}
      {% elif post_list %}
        <h2 class="text-muted text-center my-5">
          Exact match not found, here are some related results!<br> <br>
        {% include 'board/posts_widget.html' with posts_list=post_list %}
      {% else %}
        <h2 class="text-muted text-center my-5">
          No posts here :(
          {% if profile.is_seller %}
            <br>Why not <a href="{% url 'board:create' %}">make one?</a>
          {% endif %}
        </h2>
      {% endif %}
    </div>
  </div>

  {% comment %} Pagination navigation {% endcomment %}
  {% if is_paginated %}
    <div class="row">
      <div class="col-12">
        <nav>
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">Previous</span>
              </li>
            {% endif %}

            {% for i in paginator.page_range %}
              {% if i == page_obj.number %}
                <li class="page-item active">
                  <span class="page-link">{{ i }}</span>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
              {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">Next</span>
              </li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>
  {% endif %}
{% endblock content %}

marketplace/templates/marketplace/board/post_update_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}Edit Post{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <h3>Edit Post: {{ object.title }}</h3>
      <form method="post" enctype="multipart/form-data">
        {% for image in inlines %}
          {% crispy image image_helper %}
        {% endfor %}
        {% crispy form %}
      </form>
    </div>
  </div>
{% endblock content %}

marketplace/templates/marketplace/board/posts_widget.html
<div class="card-deck">
  {% for post in posts_list %}
    {% include 'board/post_card_widget.html' with post=post %}
    {# HACK: Grid splits hack for responsive card-deck #}
    {# Each split is only visible at one break point #}
    {% if forloop.counter|divisibleby:2 %}
      {# wrap every 2 on sm #}
      <div class="w-100 d-none d-sm-block d-md-none"></div>
    {% endif %}
    {% if forloop.counter|divisibleby:3 %}
      {# wrap every 3 on md #}
      <div class="w-100 d-none d-md-block d-lg-none"></div>
    {% endif %}
    {% if forloop.counter|divisibleby:4 %}
      {# wrap every 4 on lg #}
      <div class="w-100 d-none d-lg-block d-xl-none"></div>
    {% endif %}
    {% if forloop.counter|divisibleby:5 %}
      {# wrap every 5 on xl #}
      <div class="w-100 d-none d-xl-block"></div>
    {% endif %}
    {# End hack #}
  {% endfor %}
</div>